In [7]:
import numpy as np
a=np.array([1,2,3,4.5])#传输列表
print(a)
b=np.array(range(10))#传入一个range
print(b)
print(type(b))
#numpy中的数组类型：ndarray
c=np.arange(10)
print(c)
#np特有办法
print(c.dtype)

[1.  2.  3.  4.5]
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
int32


In [13]:
t4=np.array(range(1,4),dtype=float)#指定数据类型
print(t4)
print(t4.dtype)
t5=np.array([1,1,0,1,0,0],dtype=bool)
print(t5)
print(t5.dtype)
#调整数据类型
t6=t5.astype("int8")
print(t6)
print(t6.dtype)

[1. 2. 3.]
float64
[ True  True False  True False False]
bool
[1 1 0 1 0 0]
int8


In [16]:
#numpy中的小数
import random
t7=np.array([random.random() for i in range(10)])
print(t7)
print(t7.dtype)
#取小数操作
t8=np.round(t7,2)
print(t8)

[0.54218293 0.00843489 0.82338704 0.6241483  0.2621995  0.71660949
 0.40937027 0.55749012 0.35375011 0.44816153]
float64
[0.54 0.01 0.82 0.62 0.26 0.72 0.41 0.56 0.35 0.45]


In [6]:
#形状
import numpy as np
t1=np.arange(12)
print(t1)
t1.shape
t2=np.array([[1,2,3],[4,5,6]])
print(t2)
t2.shape
#输出分别是行数和列数

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[1 2 3]
 [4 5 6]]


(2, 3)

In [12]:
t3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(t3)
t3.shape
#一个三维数组

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


(2, 2, 3)

In [10]:
t4=np.arange(12)
print(t4)
t4.reshape(3,4)
#变为三行四列的数组

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
t5=np.arange(24).reshape(2,3,4)
print(t5)
t5.reshape((4,6))
t5.reshape((1,24))
#嵌套括号，二维数组
t5.flatten()
#按行展开,reshape不改变数据本身
print(t5)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [33]:
#数组计算
print(t5+2)
#广播机制，运算应用到每一个数字
print(t5/0)
#nan:not a number,inf:无限

[[[ 2  3  4  5]
  [ 6  7  8  9]
  [10 11 12 13]]

 [[14 15 16 17]
  [18 19 20 21]
  [22 23 24 25]]]
[[[nan inf inf inf]
  [inf inf inf inf]
  [inf inf inf inf]]

 [[inf inf inf inf]
  [inf inf inf inf]
  [inf inf inf inf]]]


C:\Users\29988\AppData\Local\Temp\ipykernel_19680\371017124.py:4: RuntimeWarning: divide by zero encountered in true_divide
  print(t5/0)
C:\Users\29988\AppData\Local\Temp\ipykernel_19680\371017124.py:4: RuntimeWarning: invalid value encountered in true_divide
  print(t5/0)


In [37]:
t6=np.arange(100,124).reshape((4,6))
print(t6)
t5=np.arange(0,24).reshape((4,6))
print(t5)
print(t5+t6)
#对应位置计算
print(t5*t6)

[[100 101 102 103 104 105]
 [106 107 108 109 110 111]
 [112 113 114 115 116 117]
 [118 119 120 121 122 123]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[100 102 104 106 108 110]
 [112 114 116 118 120 122]
 [124 126 128 130 132 134]
 [136 138 140 142 144 146]]
[[   0  101  204  309  416  525]
 [ 636  749  864  981 1100 1221]
 [1344 1469 1596 1725 1856 1989]
 [2124 2261 2400 2541 2684 2829]]


In [41]:
t7=np.arange(0,6)
print(t7)
print(t5)
print(t5-t7)
#t5的每一行对t7的一行进行计算
t8=np.arange(4).reshape((4,1))
print(t8)
print(t5-t8)
#列上进行运算（两者相同）
#要有相同的地方才可以计算，也就是某一维度上是相同的

[0 1 2 3 4 5]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  0  0  0  0  0]
 [ 6  6  6  6  6  6]
 [12 12 12 12 12 12]
 [18 18 18 18 18 18]]
[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3  4  5]
 [ 5  6  7  8  9 10]
 [10 11 12 13 14 15]
 [15 16 17 18 19 20]]
