In [1]:
import numpy as np
a=np.array([1,2,3,4.5])#传输列表
print(a)
b=np.array(range(10))#传入一个range
print(b)
print(type(b))
#numpy中的数组类型：ndarray
c=np.arange(10)
print(c)
#np特有办法
print(c.dtype)

[1.  2.  3.  4.5]
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
int32


In [2]:
t4=np.array(range(1,4),dtype=float)#指定数据类型
print(t4)
print(t4.dtype)
t5=np.array([1,1,0,1,0,0],dtype=bool)
print(t5)
print(t5.dtype)
#调整数据类型
t6=t5.astype("int8")
print(t6)
print(t6.dtype)

[1. 2. 3.]
float64
[ True  True False  True False False]
bool
[1 1 0 1 0 0]
int8


In [3]:
#numpy中的小数
import random
t7=np.array([random.random() for i in range(10)])
print(t7)
print(t7.dtype)
#取小数操作
t8=np.round(t7,2)
print(t8)

[0.86636237 0.53831725 0.85878842 0.3551559  0.77089052 0.10314143
 0.96189131 0.33217818 0.77006695 0.59132524]
float64
[0.87 0.54 0.86 0.36 0.77 0.1  0.96 0.33 0.77 0.59]


In [4]:
#形状
import numpy as np
t1=np.arange(12)
print(t1)
t1.shape
t2=np.array([[1,2,3],[4,5,6]])
print(t2)
t2.shape
#输出分别是行数和列数

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[1 2 3]
 [4 5 6]]


(2, 3)

In [5]:
t3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(t3)
t3.shape
#一个三维数组

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


(2, 2, 3)

In [6]:
t4=np.arange(12)
print(t4)
t4.reshape(3,4)
#变为三行四列的数组

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
t5=np.arange(24).reshape(2,3,4)
print(t5)
t5.reshape((4,6))
t5.reshape((1,24))
#嵌套括号，二维数组
t5.flatten()
#按行展开,reshape不改变数据本身
print(t5)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [8]:
#数组计算
print(t5+2)
#广播机制，运算应用到每一个数字
print(t5/0)
#nan:not a number,inf:无限

[[[ 2  3  4  5]
  [ 6  7  8  9]
  [10 11 12 13]]

 [[14 15 16 17]
  [18 19 20 21]
  [22 23 24 25]]]
[[[nan inf inf inf]
  [inf inf inf inf]
  [inf inf inf inf]]

 [[inf inf inf inf]
  [inf inf inf inf]
  [inf inf inf inf]]]


C:\Users\29988\AppData\Local\Temp\ipykernel_12152\371017124.py:4: RuntimeWarning: divide by zero encountered in true_divide
  print(t5/0)
C:\Users\29988\AppData\Local\Temp\ipykernel_12152\371017124.py:4: RuntimeWarning: invalid value encountered in true_divide
  print(t5/0)


In [9]:
t6=np.arange(100,124).reshape((4,6))
print(t6)
t5=np.arange(0,24).reshape((4,6))
print(t5)
print(t5+t6)
#对应位置计算
print(t5*t6)

[[100 101 102 103 104 105]
 [106 107 108 109 110 111]
 [112 113 114 115 116 117]
 [118 119 120 121 122 123]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[100 102 104 106 108 110]
 [112 114 116 118 120 122]
 [124 126 128 130 132 134]
 [136 138 140 142 144 146]]
[[   0  101  204  309  416  525]
 [ 636  749  864  981 1100 1221]
 [1344 1469 1596 1725 1856 1989]
 [2124 2261 2400 2541 2684 2829]]


In [10]:
t7=np.arange(0,6)
print(t7)
print(t5)
print(t5-t7)
#t5的每一行对t7的一行进行计算
t8=np.arange(4).reshape((4,1))
print(t8)
print(t5-t8)
#列上进行运算（两者相同）
#要有相同的地方才可以计算，也就是某一维度上是相同的

[0 1 2 3 4 5]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  0  0  0  0  0]
 [ 6  6  6  6  6  6]
 [12 12 12 12 12 12]
 [18 18 18 18 18 18]]
[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3  4  5]
 [ 5  6  7  8  9 10]
 [10 11 12 13 14 15]
 [15 16 17 18 19 20]]


In [11]:
#轴，方向，比如一维数组只有零轴
#0轴，1轴，2轴
#块，行，列
#np读取数据：
#np.loadtxt(frame.dtype=np.float,delimiter=None,skiprows=0,usecols=None,unpack=False)
t2=np.arange(24).reshape((4,6))
print(t2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [12]:
t2.transpose()
#转置

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

In [13]:
t2.T
t2.swapaxes(1,0)
#都是转置 

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

In [14]:
#numpy的索引和切片
print(t2[2])#取第三行

[12 13 14 15 16 17]


In [15]:
#取多行
print(t2[2:])
#取不连续的多行
print(t2[[1,3]])
#取列
print(t2[:,0])
#取连续的多列
print(t2[:2:])
#取不连续的多列
print(t2[:,[0,2]])
#取多行多列，第三行第四列
a=t2[2,3]
print(a)
print(type(a))
#取第三行到第五行，第二列到第三列
b=t2[2:5,1:4]
print(b)
#取的是行和列交叉点的值
c=t2[[0,2],[0,1]]
print(c)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 6  7  8  9 10 11]
 [18 19 20 21 22 23]]
[ 0  6 12 18]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  2]
 [ 6  8]
 [12 14]
 [18 20]]
15
<class 'numpy.int32'>
[[13 14 15]
 [19 20 21]]
[ 0 13]


In [16]:
#数值的修改
#t[:,2:4]=0,类似赋值
print(t2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [17]:
print(t2<10)
t2[t2<10]=3
print(t2)

[[ True  True  True  True  True  True]
 [ True  True  True  True False False]
 [False False False False False False]
 [False False False False False False]]
[[ 3  3  3  3  3  3]
 [ 3  3  3  3 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [18]:
#where运算符,bool索引操作
np.where(t2<10,0,10)
#clip裁剪
t2.clip(10,18)#小于10的替换成10，大于10的替换成18

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 18, 18, 18, 18, 18]])

In [19]:
#数组的拼接，两组数据变成一组
#从上往下，或者从左往右
#np.vstack((t1,t2)),竖直拼接
#np.hstack((t1,t2)),水平拼接
#拼接和分割基本相同
#交换
t2[[1,2],:]=t2[[2,1],:]
print(t2)

[[ 3  3  3  3  3  3]
 [12 13 14 15 16 17]
 [ 3  3  3  3 10 11]
 [18 19 20 21 22 23]]


In [20]:
#numpy的一些其他用法
#获取最大最小值的位置
#获取一个全零数组
np.zeros((3,4))
#创建一个全一数组
np.ones((3,4))
#创建一个对角线为1的正方形数组（方阵）：
t=np.eye(3)
#np.argmax(t,aixs=0)
#np.argmin(t,axis=1)

In [22]:
#生成随机数
np.random.randint(10,20,(4,5))#四行五列，十到二十的随机数
#np.random.uniform 小数
#种子,生成和上次一样的随机数
np.random.seed(10)
t=np.random.randint(0,20,(3,4))
print(t)
#视图 复制
a=b[:]
a=b.copy#ab不会相互影响

[[ 9  4 15  0]
 [17 16 17  8]
 [ 9  0 10  8]]


In [23]:
#nan和inf
np.nan==np.nan

False

In [24]:
np.nan!=np.nan

True

In [26]:
np.count_nonzero(t)#不为0
np.isnan(t)#统计nan的个数

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [28]:
np.sum(t2)#求和
np.sum(t2,axis=0 )#指定一个轴

array([36, 38, 40, 42, 51, 54])

In [29]:
#常用统计函数
t.sum(axis=None)
t.mean(axis=0)
np.median(t2,axis=0)
t2.max(axis=0)
t2.min(axis=0)
#极值，标准差
np.pyp(t,axis=None)
t.std(axis=None)#数据的稳定情况

AttributeError: module 'numpy' has no attribute 'pyp'

In [31]:
t1=np.arange(12).reshape((3,4)).astype("float")
t1[1,2:]=np.nan

print(t1)

[[ 0.  1.  2.  3.]
 [ 4.  5. nan nan]
 [ 8.  9. 10. 11.]]


In [35]:
def fill_ndarray(t1):
    for i in range(t1.shape[1]):
        temp_col=t1[:,i]#当前的一列
        nan_num=np.count_nonzero(temp_col!=temp_col)
        if nan_num!=0:#不为0，说明当前一列有nan
            temp_not_nan_col=temp_col[temp_col==temp_col]#当前一列不为nan的array
        
            temp_col[np.isnan(temp_col)]=temp_not_nan_col.mean()#选中nan的位置，把值赋值为均值
        
    return t1  

In [36]:
t1=fill_ndarray(t1)
print(t1)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
